# Generated by Django 5.2.6 on 2025-09-18 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work001.category', verbose_name='カテゴリ')),
            ],
        ),
    ]
