# Generated by Django 5.2.6 on 2025-09-18 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work001', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_income',
            field=models.BooleanField(default=False, verbose_name='収入カテゴリか？'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
                ('category', models.ForeignKey(limit_choices_to={'is_income': True}, on_delete=django.db.models.deletion.CASCADE, to='work001.category', verbose_name='カテゴリ')),
            ],
        ),
    ]
