# Generated by Django 5.2.6 on 2026-01-22 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('expire_date', models.DateField()),
                ('storage_type', models.CharField(choices=[('fridge', '冷蔵'), ('freezer', '冷凍'), ('room', '常温')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RecipePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required_quantity', models.IntegerField()),
                ('recipe_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.recipeplan')),
            ],
        ),
    ]
