# Generated by Django 5.2.6 on 2025-11-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_foodentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bp_sys', models.IntegerField(blank=True, null=True, verbose_name='Systolic BP')),
                ('bp_dia', models.IntegerField(blank=True, null=True, verbose_name='Diastolic BP')),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('burned_calories', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('intake_calories', models.IntegerField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
