# Generated by Django 5.2.6 on 2025-11-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='calorie_intake',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='diastolic',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='systolic',
        ),
        migrations.AddField(
            model_name='entry',
            name='bp_dia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Diastolic BP'),
        ),
        migrations.AddField(
            model_name='entry',
            name='bp_sys',
            field=models.IntegerField(blank=True, null=True, verbose_name='Systolic BP'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
