# Generated by Django 5.2.6 on 2025-11-20 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_entry_calorie_intake_remove_entry_diastolic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='food',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='calories_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='tracker.measurement'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='name',
            field=models.CharField(default='不明', max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='grams',
            field=models.FloatField(default=0),
        ),
    ]
