# Generated by Django 5.2.6 on 2025-12-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_foodentry_entry_remove_foodentry_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='calories_per_100g',
        ),
    ]
