# Generated by Django 5.2.6 on 2025-12-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_foodentry_calories_per_100g'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='kcal_per_100g',
            field=models.FloatField(default=0),
        ),
    ]
